services:
  db:
    image: mariadb:latest
    container_name: wordpress_db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "Mbaghaei42"
      MARIADB_DATABASE: "wordpress"
      MARIADB_USER: "wpuser"
      MARIADB_PASSWORD: "wppassword"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: wordpress_redis
    restart: unless-stopped
    command: redis-server --maxmemory 512mb --maxmemory-policy allkeys-lru --save 60 1000
    volumes:
      - redis_data:/data
    networks:
      - wordpress_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordpress_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "wpuser"
      WORDPRESS_DB_PASSWORD: "wppassword"
      WORDPRESS_DB_NAME: "wordpress"
      WORDPRESS_REDIS_HOST: "redis"
      WORDPRESS_REDIS_PORT: "6379"
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wordpress_network

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: wordpress_nginx
    restart: unless-stopped
    depends_on:
      - wordpress
    # برای تست لوکال این خط را uncomment کنید:
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - nginx_cache:/var/cache/nginx
    networks:
      - wordpress_network
    labels:
      - "coolify.managed=true"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wordpress_phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: "db"
      PMA_USER: "root"
      PMA_PASSWORD: "Mbaghaei42"
      PMA_ARBITRARY: "1"
    networks:
      - wordpress_network
    # برای تست لوکال این خط را uncomment کنید:
    # ports:
    #   - "8091:80"
    profiles:
      - development

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  wordpress_data:
    driver: local
  nginx_cache:
    driver: local

networks:
  wordpress_network:
    driver: bridge
